# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'SofaAcademyMarch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SofaAcademyMarch
  pod 'SnapKit', '~> 5.0.0'

end
